- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Remove old Docker APT repo (if any)
  file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent
    
- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker Packages
  apt:
    name: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    state: present
    update_cache: yes

- name: Ensure Docker is Running
  service: 
    name: docker
    state: started
    enabled: true

- name: Create app directory
  file:
    path: /opt/docker-app
    state: directory
    mode: '0755'

- name: Copy app.py to target
  copy: 
    src: app.py
    dest: /opt/docker-app/app.py

- name: Copy Dockerfile to target
  template: 
    src: Dockerfile.j2
    dest: /opt/docker-app/Dockerfile

- name: Build Docker Image
  command: docker build -t ansible-flask-app /opt/docker-app

- name: Run Docker Image
  docker_container:
    name: ansible-flask-container
    image: ansible-flask-app
    state: started
    ports:
      - "5000:5000"