pipeline {
    agent any

    environment {
        IMAGE_NAME = "dockerized-python-jenkins"
        DOCKERFILE_DIR = "Dockerized-Python-Jenkins"
    }

    stages {
        stage('Clone Repo') {
            steps {
                echo "Cloning repository..."
                git url: 'https://github.com/gowthamselvarajgit/Jenkins_Learn.git', branch: 'main'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building Docker image..."
                script {
                    dockerImage = docker.build(IMAGE_NAME, DOCKERFILE_DIR)
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                echo "Running Docker container..."
                script {
                    dockerImage.run('--rm') // '--rm' will auto-remove the container after execution
                }
            }
        }
    }
}
