pipeline {
    agent any

    environment {
        REMOTE_HOST = "192.168.20.73"
        INVENTORY_FILE = "inventory.ini"
        PLAYBOOK_FILE = "playbook.yml"
    }

    stages {
        stage('Checkout Repo') {
            steps {
                git url: 'https://github.com/gowthamselvarajgit/Jenkins_Learn.git', branch: 'main'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    # Clean old Docker repo files
                    sudo rm -f /etc/apt/sources.list.d/docker.list
                    sudo rm -f /usr/share/keyrings/docker.gpg

                    # Add GPG key
                    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker.gpg

                    # Add Docker repo with signed-by
                    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

                    # Update and install packages
                    sudo apt-get update
                    sudo apt-get install -y docker-ce docker-ce-cli containerd.io ansible
                '''
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                dir('ansible-docker-app') {
                    sh '''
                        ansible-playbook -i inventory.ini playbook.yml
                    '''
                }
            }
        }

        stage('Verify Docker Container') {
            steps {
                sh '''
                    docker ps | grep ansible-flask-container
                '''
            }
        }
    }

    post {
        failure {
            echo "❌ Build failed. Check logs above!"
        }
        success {
            echo "✅ Build and deployment completed successfully!"
        }
    }
}
