pipeline {
    agent any 

    stages{
        stage('Clone Dev Branch'){
            steps{
                echo 'Cloning dev Branch'
                checkout([
                    $class: 'GitSCM',
                    branches: [[name:'*/gitnew']],
                    userRemoteConfigs: [[url: 'https://github.com/gowthamselvarajgit/LearnGit1.git']]
                ])
            }
        }

        stage('Verify Branch'){
            steps{
                echo 'Checkng current branch'
                sh 'git branch'
            }
        }
    }
}