pipeline {
    agent any 

    stages{
        stage('Clone Dev Branch'){
            steps{
                echo 'Cloning gitnew branch...'
                git branch: 'gitnew', url: 'https://github.com/gowthamselvarajgit/LearnGit1.git'

            }
        }

        stage('Verify Branch'){
            steps{
                echo 'Checking current branch'
                sh 'git branch'
            }
        }
    }
}