pipeline {
    agent any 

    environment{
        IMAGE_NAME = "my-app-image"
    }

    stages{
        stage('Clone Repo'){
            steps{
                git url: "https://github.com/gowthamselvarajgit/Jenkins_Learn.git", branch: 'main'
            }
        }

        stage('Terraform Init and Apply'){
            steps{
                withCredentials([usernamePassword(
                    credentialsId: 'aws_creds',
                    usernameVariable: 'AWS_ACCESS_KEY_ID',
                    passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                )]){
                    dir('DynamicEC2Docker/terraform') {
                        sh '''
                            terraform init
                            terraform apply -auto-approve \
                                -var="aws_access_key=$AWS_ACCESS_KEY_ID"\
                                -var="aws_secret_key=$AWS_SECRET_ACCESS_KEY"
                        '''
                    }
                }
            }
        }

        stage('Build Docker Image'){
            steps{
                sh 'docker build -t ${IMAGE_NAME} app'
            }
        }

        stage('Run Docker with EC2 IP'){
            steps{
                script{
                    def ec2_ip = sh(script: 'cd terraform && terraform output -raw instance_ip', returnStdout: true).trim()
                    echo "EC2 IP: ${ec2_ip}"
                    sh "docker run --rm --add-host backend-server:${ec2_ip} ${IMAGE_NAME}"
                }
            }
        }
    }
}