pipeline {
    agent any 

    stages{
        stage('Pull Code') {
            steps{
                git url: 'https://github.com/gowthamselvarajgit/LearnGit1.git', branch: 'main'
            }
        }
        stage('Build'){
            steps{
                echo 'Building the project'
                sh 'git log -1 --oneline'
            }
        }
    }
}