pipeline {
    agent any 
    
    stages{
        stage('Clone Repository...'){
            steps{
                echo 'Cloning the code from github...'
            }
        }

        stage('Set permission'){
                steps{
                    echo "Making build.sh executable..."
                    sh 'chmod +x JavaGitBuildJob/build.sh'
                }
        }

        stage('Run Build Script'){
            steps{
                echo "Running build.sh..."
                sh './JavaGitBuildJob/build.sh'
            }
        }
    }
}