pipeline {
    agent any

    environment {
        // For Secret File PEM
        PEM_FILE = credentials('ec2_ssh_key')
    }

    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/gowthamselvarajgit/Jenkins_Learn.git', branch: 'main'
            }
        }

        stage('Terraform Init & Apply') {
            steps {
                dir('terraform') {
                    withCredentials([usernamePassword(credentialsId: 'AWS_CREDENTIALS', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                        sh 'terraform init'
                        sh 'terraform apply -auto-approve'
                    }
                }
            }
        }

        stage('Generate Ansible Inventory') {
            steps {
                dir('ansible') {
                    sh 'chmod +x generate_inventory.sh'
                    sh "./generate_inventory.sh $PEM_FILE"
                }
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                dir('ansible') {
                    sh 'ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.ini install_app.yml'
                }
            }
        }
    }

    post {
        success {
            echo "App deployed successfully!"
        }
        failure {
            echo "Pipeline failed. Check logs."
        }
    }
}
