pipeline {
    agent any

    environment {
        IMAGE_NAME = "testcase-docker-pipeline-image"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git url: 'https://github.com/gowthamselvarajgit/Jenkins_Learn.git', branch: 'main'
            }
        }

        stage('List Repo Contents'){
            steps{
                sh 'ls -la'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${IMAGE_NAME} TestCaseDockerPipeline"
            }
        }

        stage('Run Test in Container') {
            steps {
                sh "docker run --rm ${IMAGE_NAME}"
            }
        }
    }
}
