- name: Install Docker on EC2
  hosts: ec2 
  become: yes
  tasks:
    - name: Update APT packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable Docker Service
      systemd:
        name: docker 
        enabled: yes
        state: started