pipeline {
    agent any 

    environment {
        IMAGE_NAME = "terraform-docker-app"
        CONTAINER_NAME = "terraform-docker-container"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git url: 'https://github.com/gowthamselvarajgit/Jenkins_Learn.git', branch: 'main'
            }
        }

        stage('Terraform Init & Plan') {
            steps {
                dir('terraform') {
                    sh 'terraform init'
                    sh 'terraform plan'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('app') {
                    sh "docker build -t ${IMAGE_NAME} ."
                }
            }
        }

        stage('Run Docker Image') {
            steps {
                sh "docker run -d --rm --name ${CONTAINER_NAME} ${IMAGE_NAME}"
            }
        }
    }

    post {
        always {
            sh "docker rm -f ${CONTAINER_NAME} || true"
        }
    }
}
