pipeline {
    agent any 

    environment {
        IMAGE_NAME = "terraform-docker-app"
        CONTAINER_NAME = "terraform-docker-container"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git url: 'https://github.com/gowthamselvarajgit/Jenkins_Learn.git', branch: 'main'
            }
        }

        stage('Check Repo Contents') {
            steps {
                sh 'echo "--- Workspace Contents ---"'
                sh 'find .'
                sh 'ls -la TerraformDockerProject/terraform'
            }
        }

        stage('Terraform Init & Plan') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'aws_creds', 
                    usernameVariable: 'AWS_ACCESS_KEY_ID', 
                    passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                )]) {
                    dir('TerraformDockerProject/terraform') {
                        sh '''
                            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
                            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
                            terraform init
                            terraform plan
                        '''
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${IMAGE_NAME} TerraformDockerProject/app"
            }
        }

        stage('Run Docker Container') {
            steps {
                sh "docker run -d --rm --name ${CONTAINER_NAME} ${IMAGE_NAME}"
            }
        }
    }

    post {
        always {
            sh "docker rm -f ${CONTAINER_NAME} || true"
        }
    }
}
